
workflows:
  version: 2

  continuation-generated-workflow:
    jobs:
        - terraform/plan:
          name: plan sbx-i01-aws-us-east-1 change
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          executor-image: << pipeline.parameters.executor-image >>
          static-analysis: false
          workspace: sbx-i01-aws-us-east-1
          var-file: sbx-i01-aws-us-east-1.auto.tfvars.json
          before-terraform:
            - set-environment:
                teller_filename: 
                instance_name: sbx-i01-aws-us-east-1
                pipeline-name: << pipeline.parameters.continuation-params >>
          filters: *on-push-main      - approve sbx-dev changes:
          type: approval
          requires:
            - plan sbx-i01-aws-us-east-1 change
          filters: *on-push-main

        - terraform/apply:
          name: apply sbx-i01-aws-us-east-1 change plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          executor-image: << pipeline.parameters.executor-image >>
          workspace: sbx-i01-aws-us-east-1
          var-file: sbx-i01-aws-us-east-1.auto.tfvars.json
          before-terraform:
            - set-environment:
                teller_filename: 
                instance_name: sbx-i01-aws-us-east-1
                pipeline-name: << pipeline.parameters.continuation-params >>
          after-terraform:
            - run-inspec-tests:
                workspace: sbx-i01-aws-us-east-1
          filters: *on-push-main
          requires:
            - approve sbx-dev changes